version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: mrp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mrp
    ports:
      - "5432:5432"
    volumes:
      - mrp_pgdata:/var/lib/postgresql/data

volumes:
  mrp_pgdata:
