services:
  postgres:
    image: postgres:18
    container_name: mrp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mrp
    ports:
      - "5432:5432"
    volumes:
      - mrp_pgdata:/var/lib/postgresql

volumes:
  mrp_pgdata:
